description: xiaohan_bert-base_nvidia-default

target:
  # which virtual cluster you belong to (msrlabs, etc.). Everyone has access to "msrlabs".
  vc: convaivc
  # physical cluster to use (cam, gcr, rr1, rr2) or Azure clusters (eu1, eu2, etc.)
  cluster: rr3

environment:
  registry: convaicontainerregistryintern.azurecr.io
  image: t-cxiaoh/bert:latest

code:
  local_dir: $CONFIG_DIR


storage:
  # You can tell PT to store results in a different container optimized for writing.
  #output:
  #  storage_account_name: convaiphilly
  #  container_name: b360
  #  # you can change the mount path to reference in your code
  #  mount_dir: /B360

  # If data is in a shared container for example, we can mount the storage to a specific path
  shared_datastore:
    storage_account_name: convaistorageinterns
    container_name: t-cxiaoh
    # you can change the mount path to reference in your code
    mount_dir: /xiaohan

# data:
#   data upload is not required for this example

# list of jobs to run, we run 2 jobs in this example
# search:
  # job_template:
    # you may use {random_string:s} to avoid job name collisions
jobs:
- name: bert-base_baseline_nvidia-default
  sku: G8
  command:
  - bash scripts/run_pretraining_bert-base_baseline.sh
  # type: grid
  # max_trials: 1
  # params:
  #   - name: mt
  #     spec: discrete
  #     values: [512]
  #   - name: uf
  #     spec: discrete
  #     values: [5]

